
CREATE TABLE author(
  ID INTEGER auto_increment PRIMARY KEY,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL
);
CREATE TABLE content(
	ID INTEGER auto_increment PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	file VARCHAR(255)
	);
CREATE TABLE publication(
	ID INTEGER auto_increment PRIMARY KEY,
	date_modification DATE NOT NULL,
	name VARCHAR(255),
	content_ID INTEGER,
	author_ID INTEGER,
	CONSTRAINT ROOM_CONSTRAINT FOREIGN KEY(content_ID) REFERENCES content(ID),
	CONSTRAINT TENANT_CONSTRAINT FOREIGN KEY(author_ID) REFERENCES author(ID)
	);